//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


InstanceGroupRole = {
  'MASTER' : 1,
  'CONTROL' : 2,
  'CORE' : 3,
  'TASK' : 4
};
JobActionOnFailure = {
  'TERMINATE_JOB' : 1,
  'TERMINATE_CLUSTER' : 2,
  'CANCEL_AND_WAIT' : 3,
  'CONTINUE' : 4
};
StateCode = {
  'C_INITED' : 0,
  'C_PROCESSING' : 1,
  'C_STARTING' : 2,
  'C_BOOSTRAPPING' : 3,
  'C_RUNNING' : 4,
  'C_WAITING' : 5,
  'C_TERMINATING' : 6,
  'C_COMPLETED' : 7,
  'C_TERMINATED' : 8,
  'C_FAILED' : 9,
  'G_INITED' : 100,
  'G_PROCESSING' : 101,
  'G_STARTING' : 102,
  'G_RUNNING' : 103,
  'G_RESIZING' : 104,
  'G_TERMINATING' : 105,
  'G_TERMINATED' : 106,
  'I_INITED' : 200,
  'I_PROCESSING' : 201,
  'I_STARTING' : 202,
  'I_RUNNING' : 203,
  'I_TERMINATING' : 204,
  'I_TERMINATED' : 205,
  'J_INITED' : 300,
  'J_PROCESSING' : 301,
  'J_SUBMITTED' : 302,
  'J_RUNNGIN' : 303,
  'J_FINISHED' : 304,
  'J_KILLED' : 305,
  'J_FAILED' : 306
};
Permission = {
  'NONE' : 0,
  'FULL_CONTROL' : 1,
  'ADMIN' : 2,
  'READ' : 3,
  'WRITE' : 4,
  'READ_WRITE' : 5,
  'READ_WRITE_ADMIN' : 6
};
Timeline = function(args) {
  this.creationTime = 0;
  this.readyTime = 0;
  this.endTime = 0;
  if (args) {
    if (args.creationTime !== undefined) {
      this.creationTime = args.creationTime;
    }
    if (args.readyTime !== undefined) {
      this.readyTime = args.readyTime;
    }
    if (args.endTime !== undefined) {
      this.endTime = args.endTime;
    }
  }
};
Timeline.prototype = {};
Timeline.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.creationTime = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.readyTime = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.endTime = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Timeline.prototype.write = function(output) {
  output.writeStructBegin('Timeline');
  if (this.creationTime !== null && this.creationTime !== undefined) {
    output.writeFieldBegin('creationTime', Thrift.Type.I32, 1);
    output.writeI32(this.creationTime);
    output.writeFieldEnd();
  }
  if (this.readyTime !== null && this.readyTime !== undefined) {
    output.writeFieldBegin('readyTime', Thrift.Type.I32, 2);
    output.writeI32(this.readyTime);
    output.writeFieldEnd();
  }
  if (this.endTime !== null && this.endTime !== undefined) {
    output.writeFieldBegin('endTime', Thrift.Type.I32, 3);
    output.writeI32(this.endTime);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Status = function(args) {
  this.state = null;
  this.stateChangeReason = null;
  this.timeline = null;
  if (args) {
    if (args.state !== undefined) {
      this.state = args.state;
    }
    if (args.stateChangeReason !== undefined) {
      this.stateChangeReason = args.stateChangeReason;
    }
    if (args.timeline !== undefined) {
      this.timeline = args.timeline;
    }
  }
};
Status.prototype = {};
Status.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.state = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.stateChangeReason = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRUCT) {
        this.timeline = new Timeline();
        this.timeline.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Status.prototype.write = function(output) {
  output.writeStructBegin('Status');
  if (this.state !== null && this.state !== undefined) {
    output.writeFieldBegin('state', Thrift.Type.I32, 1);
    output.writeI32(this.state);
    output.writeFieldEnd();
  }
  if (this.stateChangeReason !== null && this.stateChangeReason !== undefined) {
    output.writeFieldBegin('stateChangeReason', Thrift.Type.STRING, 2);
    output.writeString(this.stateChangeReason);
    output.writeFieldEnd();
  }
  if (this.timeline !== null && this.timeline !== undefined) {
    output.writeFieldBegin('timeline', Thrift.Type.STRUCT, 3);
    this.timeline.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

InstanceTypeInfo = function(args) {
  this.name = null;
  this.cpu = null;
  this.ram = null;
  this.disk = null;
  if (args) {
    if (args.name !== undefined) {
      this.name = args.name;
    }
    if (args.cpu !== undefined) {
      this.cpu = args.cpu;
    }
    if (args.ram !== undefined) {
      this.ram = args.ram;
    }
    if (args.disk !== undefined) {
      this.disk = args.disk;
    }
  }
};
InstanceTypeInfo.prototype = {};
InstanceTypeInfo.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.cpu = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.ram = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.disk = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InstanceTypeInfo.prototype.write = function(output) {
  output.writeStructBegin('InstanceTypeInfo');
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 1);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.cpu !== null && this.cpu !== undefined) {
    output.writeFieldBegin('cpu', Thrift.Type.I32, 2);
    output.writeI32(this.cpu);
    output.writeFieldEnd();
  }
  if (this.ram !== null && this.ram !== undefined) {
    output.writeFieldBegin('ram', Thrift.Type.I32, 3);
    output.writeI32(this.ram);
    output.writeFieldEnd();
  }
  if (this.disk !== null && this.disk !== undefined) {
    output.writeFieldBegin('disk', Thrift.Type.I32, 4);
    output.writeI32(this.disk);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

EMRUser = function(args) {
  this.developerId = null;
  this.clusterIds = null;
  if (args) {
    if (args.developerId !== undefined) {
      this.developerId = args.developerId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field developerId is unset!');
    }
    if (args.clusterIds !== undefined) {
      this.clusterIds = args.clusterIds;
    }
  }
};
EMRUser.prototype = {};
EMRUser.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.developerId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.clusterIds = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = input.readString().value;
          this.clusterIds.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

EMRUser.prototype.write = function(output) {
  output.writeStructBegin('EMRUser');
  if (this.developerId !== null && this.developerId !== undefined) {
    output.writeFieldBegin('developerId', Thrift.Type.STRING, 1);
    output.writeString(this.developerId);
    output.writeFieldEnd();
  }
  if (this.clusterIds !== null && this.clusterIds !== undefined) {
    output.writeFieldBegin('clusterIds', Thrift.Type.LIST, 2);
    output.writeListBegin(Thrift.Type.STRING, this.clusterIds.length);
    for (var iter7 in this.clusterIds)
    {
      if (this.clusterIds.hasOwnProperty(iter7))
      {
        iter7 = this.clusterIds[iter7];
        output.writeString(iter7);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AddInstanceGroupRequest = function(args) {
  this.name = null;
  this.clusterId = null;
  this.role = null;
  this.instanceType = null;
  this.requestedInstanceCount = null;
  if (args) {
    if (args.name !== undefined) {
      this.name = args.name;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field name is unset!');
    }
    if (args.clusterId !== undefined) {
      this.clusterId = args.clusterId;
    }
    if (args.role !== undefined) {
      this.role = args.role;
    }
    if (args.instanceType !== undefined) {
      this.instanceType = args.instanceType;
    }
    if (args.requestedInstanceCount !== undefined) {
      this.requestedInstanceCount = args.requestedInstanceCount;
    }
  }
};
AddInstanceGroupRequest.prototype = {};
AddInstanceGroupRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.clusterId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.role = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.instanceType = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I32) {
        this.requestedInstanceCount = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AddInstanceGroupRequest.prototype.write = function(output) {
  output.writeStructBegin('AddInstanceGroupRequest');
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 1);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.clusterId !== null && this.clusterId !== undefined) {
    output.writeFieldBegin('clusterId', Thrift.Type.STRING, 2);
    output.writeString(this.clusterId);
    output.writeFieldEnd();
  }
  if (this.role !== null && this.role !== undefined) {
    output.writeFieldBegin('role', Thrift.Type.I32, 3);
    output.writeI32(this.role);
    output.writeFieldEnd();
  }
  if (this.instanceType !== null && this.instanceType !== undefined) {
    output.writeFieldBegin('instanceType', Thrift.Type.STRING, 4);
    output.writeString(this.instanceType);
    output.writeFieldEnd();
  }
  if (this.requestedInstanceCount !== null && this.requestedInstanceCount !== undefined) {
    output.writeFieldBegin('requestedInstanceCount', Thrift.Type.I32, 5);
    output.writeI32(this.requestedInstanceCount);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AddInstanceGroupResponse = function(args) {
  this.instanceGroupId = null;
  this.name = null;
  this.clusterId = null;
  if (args) {
    if (args.instanceGroupId !== undefined) {
      this.instanceGroupId = args.instanceGroupId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field instanceGroupId is unset!');
    }
    if (args.name !== undefined) {
      this.name = args.name;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field name is unset!');
    }
    if (args.clusterId !== undefined) {
      this.clusterId = args.clusterId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field clusterId is unset!');
    }
  }
};
AddInstanceGroupResponse.prototype = {};
AddInstanceGroupResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.instanceGroupId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.clusterId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AddInstanceGroupResponse.prototype.write = function(output) {
  output.writeStructBegin('AddInstanceGroupResponse');
  if (this.instanceGroupId !== null && this.instanceGroupId !== undefined) {
    output.writeFieldBegin('instanceGroupId', Thrift.Type.STRING, 1);
    output.writeString(this.instanceGroupId);
    output.writeFieldEnd();
  }
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 2);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.clusterId !== null && this.clusterId !== undefined) {
    output.writeFieldBegin('clusterId', Thrift.Type.STRING, 3);
    output.writeString(this.clusterId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SubmitJobRequest = function(args) {
  this.name = null;
  this.clusterId = null;
  this.jar = null;
  this.jarMainClass = null;
  this.jarArgs = null;
  this.jarProperties = null;
  this.actionOnFailure = null;
  if (args) {
    if (args.name !== undefined) {
      this.name = args.name;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field name is unset!');
    }
    if (args.clusterId !== undefined) {
      this.clusterId = args.clusterId;
    }
    if (args.jar !== undefined) {
      this.jar = args.jar;
    }
    if (args.jarMainClass !== undefined) {
      this.jarMainClass = args.jarMainClass;
    }
    if (args.jarArgs !== undefined) {
      this.jarArgs = args.jarArgs;
    }
    if (args.jarProperties !== undefined) {
      this.jarProperties = args.jarProperties;
    }
    if (args.actionOnFailure !== undefined) {
      this.actionOnFailure = args.actionOnFailure;
    }
  }
};
SubmitJobRequest.prototype = {};
SubmitJobRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.clusterId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.jar = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.jarMainClass = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.LIST) {
        var _size8 = 0;
        var _rtmp312;
        this.jarArgs = [];
        var _etype11 = 0;
        _rtmp312 = input.readListBegin();
        _etype11 = _rtmp312.etype;
        _size8 = _rtmp312.size;
        for (var _i13 = 0; _i13 < _size8; ++_i13)
        {
          var elem14 = null;
          elem14 = input.readString().value;
          this.jarArgs.push(elem14);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.MAP) {
        var _size15 = 0;
        var _rtmp319;
        this.jarProperties = {};
        var _ktype16 = 0;
        var _vtype17 = 0;
        _rtmp319 = input.readMapBegin();
        _ktype16 = _rtmp319.ktype;
        _vtype17 = _rtmp319.vtype;
        _size15 = _rtmp319.size;
        for (var _i20 = 0; _i20 < _size15; ++_i20)
        {
          if (_i20 > 0 ) {
            if (input.rstack.length > input.rpos[input.rpos.length -1] + 1) {
              input.rstack.pop();
            }
          }
          var key21 = null;
          var val22 = null;
          key21 = input.readString().value;
          val22 = input.readString().value;
          this.jarProperties[key21] = val22;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.I32) {
        this.actionOnFailure = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SubmitJobRequest.prototype.write = function(output) {
  output.writeStructBegin('SubmitJobRequest');
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 1);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.clusterId !== null && this.clusterId !== undefined) {
    output.writeFieldBegin('clusterId', Thrift.Type.STRING, 2);
    output.writeString(this.clusterId);
    output.writeFieldEnd();
  }
  if (this.jar !== null && this.jar !== undefined) {
    output.writeFieldBegin('jar', Thrift.Type.STRING, 3);
    output.writeString(this.jar);
    output.writeFieldEnd();
  }
  if (this.jarMainClass !== null && this.jarMainClass !== undefined) {
    output.writeFieldBegin('jarMainClass', Thrift.Type.STRING, 4);
    output.writeString(this.jarMainClass);
    output.writeFieldEnd();
  }
  if (this.jarArgs !== null && this.jarArgs !== undefined) {
    output.writeFieldBegin('jarArgs', Thrift.Type.LIST, 5);
    output.writeListBegin(Thrift.Type.STRING, this.jarArgs.length);
    for (var iter23 in this.jarArgs)
    {
      if (this.jarArgs.hasOwnProperty(iter23))
      {
        iter23 = this.jarArgs[iter23];
        output.writeString(iter23);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.jarProperties !== null && this.jarProperties !== undefined) {
    output.writeFieldBegin('jarProperties', Thrift.Type.MAP, 6);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRING, Thrift.objectLength(this.jarProperties));
    for (var kiter24 in this.jarProperties)
    {
      if (this.jarProperties.hasOwnProperty(kiter24))
      {
        var viter25 = this.jarProperties[kiter24];
        output.writeString(kiter24);
        output.writeString(viter25);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  if (this.actionOnFailure !== null && this.actionOnFailure !== undefined) {
    output.writeFieldBegin('actionOnFailure', Thrift.Type.I32, 7);
    output.writeI32(this.actionOnFailure);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SubmitJobResponse = function(args) {
  this.jobId = null;
  this.name = null;
  this.clusterId = null;
  if (args) {
    if (args.jobId !== undefined) {
      this.jobId = args.jobId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field jobId is unset!');
    }
    if (args.name !== undefined) {
      this.name = args.name;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field name is unset!');
    }
    if (args.clusterId !== undefined) {
      this.clusterId = args.clusterId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field clusterId is unset!');
    }
  }
};
SubmitJobResponse.prototype = {};
SubmitJobResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.jobId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.clusterId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SubmitJobResponse.prototype.write = function(output) {
  output.writeStructBegin('SubmitJobResponse');
  if (this.jobId !== null && this.jobId !== undefined) {
    output.writeFieldBegin('jobId', Thrift.Type.STRING, 1);
    output.writeString(this.jobId);
    output.writeFieldEnd();
  }
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 2);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.clusterId !== null && this.clusterId !== undefined) {
    output.writeFieldBegin('clusterId', Thrift.Type.STRING, 3);
    output.writeString(this.clusterId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

CreateClusterRequest = function(args) {
  this.name = null;
  this.autoTerminate = false;
  this.terminationProtected = true;
  this.region = null;
  this.purpose = null;
  this.keyPair = null;
  this.addInstanceGroupRequests = null;
  this.submitJobRequests = null;
  if (args) {
    if (args.name !== undefined) {
      this.name = args.name;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field name is unset!');
    }
    if (args.autoTerminate !== undefined) {
      this.autoTerminate = args.autoTerminate;
    }
    if (args.terminationProtected !== undefined) {
      this.terminationProtected = args.terminationProtected;
    }
    if (args.region !== undefined) {
      this.region = args.region;
    }
    if (args.purpose !== undefined) {
      this.purpose = args.purpose;
    }
    if (args.keyPair !== undefined) {
      this.keyPair = args.keyPair;
    }
    if (args.addInstanceGroupRequests !== undefined) {
      this.addInstanceGroupRequests = args.addInstanceGroupRequests;
    }
    if (args.submitJobRequests !== undefined) {
      this.submitJobRequests = args.submitJobRequests;
    }
  }
};
CreateClusterRequest.prototype = {};
CreateClusterRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.BOOL) {
        this.autoTerminate = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BOOL) {
        this.terminationProtected = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.region = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.purpose = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.STRING) {
        this.keyPair = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.LIST) {
        var _size26 = 0;
        var _rtmp330;
        this.addInstanceGroupRequests = [];
        var _etype29 = 0;
        _rtmp330 = input.readListBegin();
        _etype29 = _rtmp330.etype;
        _size26 = _rtmp330.size;
        for (var _i31 = 0; _i31 < _size26; ++_i31)
        {
          var elem32 = null;
          elem32 = new AddInstanceGroupRequest();
          elem32.read(input);
          this.addInstanceGroupRequests.push(elem32);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.LIST) {
        var _size33 = 0;
        var _rtmp337;
        this.submitJobRequests = [];
        var _etype36 = 0;
        _rtmp337 = input.readListBegin();
        _etype36 = _rtmp337.etype;
        _size33 = _rtmp337.size;
        for (var _i38 = 0; _i38 < _size33; ++_i38)
        {
          var elem39 = null;
          elem39 = new SubmitJobRequest();
          elem39.read(input);
          this.submitJobRequests.push(elem39);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CreateClusterRequest.prototype.write = function(output) {
  output.writeStructBegin('CreateClusterRequest');
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 1);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.autoTerminate !== null && this.autoTerminate !== undefined) {
    output.writeFieldBegin('autoTerminate', Thrift.Type.BOOL, 2);
    output.writeBool(this.autoTerminate);
    output.writeFieldEnd();
  }
  if (this.terminationProtected !== null && this.terminationProtected !== undefined) {
    output.writeFieldBegin('terminationProtected', Thrift.Type.BOOL, 3);
    output.writeBool(this.terminationProtected);
    output.writeFieldEnd();
  }
  if (this.region !== null && this.region !== undefined) {
    output.writeFieldBegin('region', Thrift.Type.STRING, 4);
    output.writeString(this.region);
    output.writeFieldEnd();
  }
  if (this.purpose !== null && this.purpose !== undefined) {
    output.writeFieldBegin('purpose', Thrift.Type.STRING, 5);
    output.writeString(this.purpose);
    output.writeFieldEnd();
  }
  if (this.keyPair !== null && this.keyPair !== undefined) {
    output.writeFieldBegin('keyPair', Thrift.Type.STRING, 6);
    output.writeString(this.keyPair);
    output.writeFieldEnd();
  }
  if (this.addInstanceGroupRequests !== null && this.addInstanceGroupRequests !== undefined) {
    output.writeFieldBegin('addInstanceGroupRequests', Thrift.Type.LIST, 7);
    output.writeListBegin(Thrift.Type.STRUCT, this.addInstanceGroupRequests.length);
    for (var iter40 in this.addInstanceGroupRequests)
    {
      if (this.addInstanceGroupRequests.hasOwnProperty(iter40))
      {
        iter40 = this.addInstanceGroupRequests[iter40];
        iter40.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.submitJobRequests !== null && this.submitJobRequests !== undefined) {
    output.writeFieldBegin('submitJobRequests', Thrift.Type.LIST, 8);
    output.writeListBegin(Thrift.Type.STRUCT, this.submitJobRequests.length);
    for (var iter41 in this.submitJobRequests)
    {
      if (this.submitJobRequests.hasOwnProperty(iter41))
      {
        iter41 = this.submitJobRequests[iter41];
        iter41.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

CreateClusterResponse = function(args) {
  this.clusterId = null;
  this.name = null;
  this.addInstanceGroupResponses = null;
  this.submitJobResponses = null;
  if (args) {
    if (args.clusterId !== undefined) {
      this.clusterId = args.clusterId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field clusterId is unset!');
    }
    if (args.name !== undefined) {
      this.name = args.name;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field name is unset!');
    }
    if (args.addInstanceGroupResponses !== undefined) {
      this.addInstanceGroupResponses = args.addInstanceGroupResponses;
    }
    if (args.submitJobResponses !== undefined) {
      this.submitJobResponses = args.submitJobResponses;
    }
  }
};
CreateClusterResponse.prototype = {};
CreateClusterResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.clusterId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.LIST) {
        var _size42 = 0;
        var _rtmp346;
        this.addInstanceGroupResponses = [];
        var _etype45 = 0;
        _rtmp346 = input.readListBegin();
        _etype45 = _rtmp346.etype;
        _size42 = _rtmp346.size;
        for (var _i47 = 0; _i47 < _size42; ++_i47)
        {
          var elem48 = null;
          elem48 = new AddInstanceGroupResponse();
          elem48.read(input);
          this.addInstanceGroupResponses.push(elem48);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.LIST) {
        var _size49 = 0;
        var _rtmp353;
        this.submitJobResponses = [];
        var _etype52 = 0;
        _rtmp353 = input.readListBegin();
        _etype52 = _rtmp353.etype;
        _size49 = _rtmp353.size;
        for (var _i54 = 0; _i54 < _size49; ++_i54)
        {
          var elem55 = null;
          elem55 = new SubmitJobResponse();
          elem55.read(input);
          this.submitJobResponses.push(elem55);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CreateClusterResponse.prototype.write = function(output) {
  output.writeStructBegin('CreateClusterResponse');
  if (this.clusterId !== null && this.clusterId !== undefined) {
    output.writeFieldBegin('clusterId', Thrift.Type.STRING, 1);
    output.writeString(this.clusterId);
    output.writeFieldEnd();
  }
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 2);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.addInstanceGroupResponses !== null && this.addInstanceGroupResponses !== undefined) {
    output.writeFieldBegin('addInstanceGroupResponses', Thrift.Type.LIST, 3);
    output.writeListBegin(Thrift.Type.STRUCT, this.addInstanceGroupResponses.length);
    for (var iter56 in this.addInstanceGroupResponses)
    {
      if (this.addInstanceGroupResponses.hasOwnProperty(iter56))
      {
        iter56 = this.addInstanceGroupResponses[iter56];
        iter56.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.submitJobResponses !== null && this.submitJobResponses !== undefined) {
    output.writeFieldBegin('submitJobResponses', Thrift.Type.LIST, 4);
    output.writeListBegin(Thrift.Type.STRUCT, this.submitJobResponses.length);
    for (var iter57 in this.submitJobResponses)
    {
      if (this.submitJobResponses.hasOwnProperty(iter57))
      {
        iter57 = this.submitJobResponses[iter57];
        iter57.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TerminateClusterRequest = function(args) {
  this.clusterId = null;
  this.force = null;
  if (args) {
    if (args.clusterId !== undefined) {
      this.clusterId = args.clusterId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field clusterId is unset!');
    }
    if (args.force !== undefined) {
      this.force = args.force;
    }
  }
};
TerminateClusterRequest.prototype = {};
TerminateClusterRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.clusterId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.BOOL) {
        this.force = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TerminateClusterRequest.prototype.write = function(output) {
  output.writeStructBegin('TerminateClusterRequest');
  if (this.clusterId !== null && this.clusterId !== undefined) {
    output.writeFieldBegin('clusterId', Thrift.Type.STRING, 1);
    output.writeString(this.clusterId);
    output.writeFieldEnd();
  }
  if (this.force !== null && this.force !== undefined) {
    output.writeFieldBegin('force', Thrift.Type.BOOL, 2);
    output.writeBool(this.force);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ModifyInstanceGroupRequest = function(args) {
  this.instanceGroupId = null;
  this.requestedInstanceCount = null;
  if (args) {
    if (args.instanceGroupId !== undefined) {
      this.instanceGroupId = args.instanceGroupId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field instanceGroupId is unset!');
    }
    if (args.requestedInstanceCount !== undefined) {
      this.requestedInstanceCount = args.requestedInstanceCount;
    }
  }
};
ModifyInstanceGroupRequest.prototype = {};
ModifyInstanceGroupRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.instanceGroupId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.requestedInstanceCount = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ModifyInstanceGroupRequest.prototype.write = function(output) {
  output.writeStructBegin('ModifyInstanceGroupRequest');
  if (this.instanceGroupId !== null && this.instanceGroupId !== undefined) {
    output.writeFieldBegin('instanceGroupId', Thrift.Type.STRING, 1);
    output.writeString(this.instanceGroupId);
    output.writeFieldEnd();
  }
  if (this.requestedInstanceCount !== null && this.requestedInstanceCount !== undefined) {
    output.writeFieldBegin('requestedInstanceCount', Thrift.Type.I32, 2);
    output.writeI32(this.requestedInstanceCount);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ModifyInstanceGroupResponse = function(args) {
};
ModifyInstanceGroupResponse.prototype = {};
ModifyInstanceGroupResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ModifyInstanceGroupResponse.prototype.write = function(output) {
  output.writeStructBegin('ModifyInstanceGroupResponse');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

KillJobRequest = function(args) {
  this.jobId = null;
  this.clusterId = null;
  if (args) {
    if (args.jobId !== undefined) {
      this.jobId = args.jobId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field jobId is unset!');
    }
    if (args.clusterId !== undefined) {
      this.clusterId = args.clusterId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field clusterId is unset!');
    }
  }
};
KillJobRequest.prototype = {};
KillJobRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.jobId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.clusterId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

KillJobRequest.prototype.write = function(output) {
  output.writeStructBegin('KillJobRequest');
  if (this.jobId !== null && this.jobId !== undefined) {
    output.writeFieldBegin('jobId', Thrift.Type.STRING, 1);
    output.writeString(this.jobId);
    output.writeFieldEnd();
  }
  if (this.clusterId !== null && this.clusterId !== undefined) {
    output.writeFieldBegin('clusterId', Thrift.Type.STRING, 2);
    output.writeString(this.clusterId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SetPermissionRequest = function(args) {
  this.resourceId = null;
  this.developerId = null;
  this.permission = null;
  if (args) {
    if (args.resourceId !== undefined) {
      this.resourceId = args.resourceId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field resourceId is unset!');
    }
    if (args.developerId !== undefined) {
      this.developerId = args.developerId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field developerId is unset!');
    }
    if (args.permission !== undefined) {
      this.permission = args.permission;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field permission is unset!');
    }
  }
};
SetPermissionRequest.prototype = {};
SetPermissionRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.resourceId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.developerId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.permission = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SetPermissionRequest.prototype.write = function(output) {
  output.writeStructBegin('SetPermissionRequest');
  if (this.resourceId !== null && this.resourceId !== undefined) {
    output.writeFieldBegin('resourceId', Thrift.Type.STRING, 1);
    output.writeString(this.resourceId);
    output.writeFieldEnd();
  }
  if (this.developerId !== null && this.developerId !== undefined) {
    output.writeFieldBegin('developerId', Thrift.Type.STRING, 2);
    output.writeString(this.developerId);
    output.writeFieldEnd();
  }
  if (this.permission !== null && this.permission !== undefined) {
    output.writeFieldBegin('permission', Thrift.Type.I32, 3);
    output.writeI32(this.permission);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

QueryPermissionRequest = function(args) {
  this.resourceId = null;
  this.developerId = null;
  if (args) {
    if (args.resourceId !== undefined) {
      this.resourceId = args.resourceId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field resourceId is unset!');
    }
    if (args.developerId !== undefined) {
      this.developerId = args.developerId;
    }
  }
};
QueryPermissionRequest.prototype = {};
QueryPermissionRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.resourceId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.developerId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

QueryPermissionRequest.prototype.write = function(output) {
  output.writeStructBegin('QueryPermissionRequest');
  if (this.resourceId !== null && this.resourceId !== undefined) {
    output.writeFieldBegin('resourceId', Thrift.Type.STRING, 1);
    output.writeString(this.resourceId);
    output.writeFieldEnd();
  }
  if (this.developerId !== null && this.developerId !== undefined) {
    output.writeFieldBegin('developerId', Thrift.Type.STRING, 2);
    output.writeString(this.developerId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

QueryPermissionResponse = function(args) {
  this.resourceId = null;
  this.permission = null;
  this.developerId = null;
  if (args) {
    if (args.resourceId !== undefined) {
      this.resourceId = args.resourceId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field resourceId is unset!');
    }
    if (args.permission !== undefined) {
      this.permission = args.permission;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field permission is unset!');
    }
    if (args.developerId !== undefined) {
      this.developerId = args.developerId;
    }
  }
};
QueryPermissionResponse.prototype = {};
QueryPermissionResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.resourceId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.permission = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.developerId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

QueryPermissionResponse.prototype.write = function(output) {
  output.writeStructBegin('QueryPermissionResponse');
  if (this.resourceId !== null && this.resourceId !== undefined) {
    output.writeFieldBegin('resourceId', Thrift.Type.STRING, 1);
    output.writeString(this.resourceId);
    output.writeFieldEnd();
  }
  if (this.permission !== null && this.permission !== undefined) {
    output.writeFieldBegin('permission', Thrift.Type.I32, 2);
    output.writeI32(this.permission);
    output.writeFieldEnd();
  }
  if (this.developerId !== null && this.developerId !== undefined) {
    output.writeFieldBegin('developerId', Thrift.Type.STRING, 3);
    output.writeString(this.developerId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

RevokePermissionRequest = function(args) {
  this.resourceId = null;
  this.developerId = null;
  if (args) {
    if (args.resourceId !== undefined) {
      this.resourceId = args.resourceId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field resourceId is unset!');
    }
    if (args.developerId !== undefined) {
      this.developerId = args.developerId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field developerId is unset!');
    }
  }
};
RevokePermissionRequest.prototype = {};
RevokePermissionRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.resourceId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.developerId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RevokePermissionRequest.prototype.write = function(output) {
  output.writeStructBegin('RevokePermissionRequest');
  if (this.resourceId !== null && this.resourceId !== undefined) {
    output.writeFieldBegin('resourceId', Thrift.Type.STRING, 1);
    output.writeString(this.resourceId);
    output.writeFieldEnd();
  }
  if (this.developerId !== null && this.developerId !== undefined) {
    output.writeFieldBegin('developerId', Thrift.Type.STRING, 2);
    output.writeString(this.developerId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ListPermissionRequest = function(args) {
  this.resourceId = null;
  if (args) {
    if (args.resourceId !== undefined) {
      this.resourceId = args.resourceId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field resourceId is unset!');
    }
  }
};
ListPermissionRequest.prototype = {};
ListPermissionRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.resourceId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ListPermissionRequest.prototype.write = function(output) {
  output.writeStructBegin('ListPermissionRequest');
  if (this.resourceId !== null && this.resourceId !== undefined) {
    output.writeFieldBegin('resourceId', Thrift.Type.STRING, 1);
    output.writeString(this.resourceId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ListPermissionResponse = function(args) {
  this.permissions = null;
  if (args) {
    if (args.permissions !== undefined) {
      this.permissions = args.permissions;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field permissions is unset!');
    }
  }
};
ListPermissionResponse.prototype = {};
ListPermissionResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.MAP) {
        var _size58 = 0;
        var _rtmp362;
        this.permissions = {};
        var _ktype59 = 0;
        var _vtype60 = 0;
        _rtmp362 = input.readMapBegin();
        _ktype59 = _rtmp362.ktype;
        _vtype60 = _rtmp362.vtype;
        _size58 = _rtmp362.size;
        for (var _i63 = 0; _i63 < _size58; ++_i63)
        {
          if (_i63 > 0 ) {
            if (input.rstack.length > input.rpos[input.rpos.length -1] + 1) {
              input.rstack.pop();
            }
          }
          var key64 = null;
          var val65 = null;
          key64 = input.readString().value;
          val65 = input.readI32().value;
          this.permissions[key64] = val65;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ListPermissionResponse.prototype.write = function(output) {
  output.writeStructBegin('ListPermissionResponse');
  if (this.permissions !== null && this.permissions !== undefined) {
    output.writeFieldBegin('permissions', Thrift.Type.MAP, 1);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.I32, Thrift.objectLength(this.permissions));
    for (var kiter66 in this.permissions)
    {
      if (this.permissions.hasOwnProperty(kiter66))
      {
        var viter67 = this.permissions[kiter66];
        output.writeString(kiter66);
        output.writeI32(viter67);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

InstanceDetail = function(args) {
  this.instanceId = null;
  this.osInstanceId = null;
  this.name = null;
  this.instanceType = null;
  this.privateIpAddress = null;
  this.publicIpAddress = null;
  this.privateDnsName = null;
  this.publicDnsName = null;
  this.instanceStatus = null;
  if (args) {
    if (args.instanceId !== undefined) {
      this.instanceId = args.instanceId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field instanceId is unset!');
    }
    if (args.osInstanceId !== undefined) {
      this.osInstanceId = args.osInstanceId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field osInstanceId is unset!');
    }
    if (args.name !== undefined) {
      this.name = args.name;
    }
    if (args.instanceType !== undefined) {
      this.instanceType = args.instanceType;
    }
    if (args.privateIpAddress !== undefined) {
      this.privateIpAddress = args.privateIpAddress;
    }
    if (args.publicIpAddress !== undefined) {
      this.publicIpAddress = args.publicIpAddress;
    }
    if (args.privateDnsName !== undefined) {
      this.privateDnsName = args.privateDnsName;
    }
    if (args.publicDnsName !== undefined) {
      this.publicDnsName = args.publicDnsName;
    }
    if (args.instanceStatus !== undefined) {
      this.instanceStatus = args.instanceStatus;
    }
  }
};
InstanceDetail.prototype = {};
InstanceDetail.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.instanceId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.osInstanceId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.instanceType = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.privateIpAddress = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.STRING) {
        this.publicIpAddress = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.STRING) {
        this.privateDnsName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.STRING) {
        this.publicDnsName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 9:
      if (ftype == Thrift.Type.STRUCT) {
        this.instanceStatus = new Status();
        this.instanceStatus.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InstanceDetail.prototype.write = function(output) {
  output.writeStructBegin('InstanceDetail');
  if (this.instanceId !== null && this.instanceId !== undefined) {
    output.writeFieldBegin('instanceId', Thrift.Type.STRING, 1);
    output.writeString(this.instanceId);
    output.writeFieldEnd();
  }
  if (this.osInstanceId !== null && this.osInstanceId !== undefined) {
    output.writeFieldBegin('osInstanceId', Thrift.Type.STRING, 2);
    output.writeString(this.osInstanceId);
    output.writeFieldEnd();
  }
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 3);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.instanceType !== null && this.instanceType !== undefined) {
    output.writeFieldBegin('instanceType', Thrift.Type.STRING, 4);
    output.writeString(this.instanceType);
    output.writeFieldEnd();
  }
  if (this.privateIpAddress !== null && this.privateIpAddress !== undefined) {
    output.writeFieldBegin('privateIpAddress', Thrift.Type.STRING, 5);
    output.writeString(this.privateIpAddress);
    output.writeFieldEnd();
  }
  if (this.publicIpAddress !== null && this.publicIpAddress !== undefined) {
    output.writeFieldBegin('publicIpAddress', Thrift.Type.STRING, 6);
    output.writeString(this.publicIpAddress);
    output.writeFieldEnd();
  }
  if (this.privateDnsName !== null && this.privateDnsName !== undefined) {
    output.writeFieldBegin('privateDnsName', Thrift.Type.STRING, 7);
    output.writeString(this.privateDnsName);
    output.writeFieldEnd();
  }
  if (this.publicDnsName !== null && this.publicDnsName !== undefined) {
    output.writeFieldBegin('publicDnsName', Thrift.Type.STRING, 8);
    output.writeString(this.publicDnsName);
    output.writeFieldEnd();
  }
  if (this.instanceStatus !== null && this.instanceStatus !== undefined) {
    output.writeFieldBegin('instanceStatus', Thrift.Type.STRUCT, 9);
    this.instanceStatus.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobDetail = function(args) {
  this.jobId = null;
  this.name = null;
  this.jar = null;
  this.jarMainClass = null;
  this.jarArgs = null;
  this.jarProperties = null;
  this.jobStatus = null;
  if (args) {
    if (args.jobId !== undefined) {
      this.jobId = args.jobId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field jobId is unset!');
    }
    if (args.name !== undefined) {
      this.name = args.name;
    }
    if (args.jar !== undefined) {
      this.jar = args.jar;
    }
    if (args.jarMainClass !== undefined) {
      this.jarMainClass = args.jarMainClass;
    }
    if (args.jarArgs !== undefined) {
      this.jarArgs = args.jarArgs;
    }
    if (args.jarProperties !== undefined) {
      this.jarProperties = args.jarProperties;
    }
    if (args.jobStatus !== undefined) {
      this.jobStatus = args.jobStatus;
    }
  }
};
JobDetail.prototype = {};
JobDetail.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.jobId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.jar = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.jarMainClass = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.LIST) {
        var _size68 = 0;
        var _rtmp372;
        this.jarArgs = [];
        var _etype71 = 0;
        _rtmp372 = input.readListBegin();
        _etype71 = _rtmp372.etype;
        _size68 = _rtmp372.size;
        for (var _i73 = 0; _i73 < _size68; ++_i73)
        {
          var elem74 = null;
          elem74 = input.readString().value;
          this.jarArgs.push(elem74);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.MAP) {
        var _size75 = 0;
        var _rtmp379;
        this.jarProperties = {};
        var _ktype76 = 0;
        var _vtype77 = 0;
        _rtmp379 = input.readMapBegin();
        _ktype76 = _rtmp379.ktype;
        _vtype77 = _rtmp379.vtype;
        _size75 = _rtmp379.size;
        for (var _i80 = 0; _i80 < _size75; ++_i80)
        {
          if (_i80 > 0 ) {
            if (input.rstack.length > input.rpos[input.rpos.length -1] + 1) {
              input.rstack.pop();
            }
          }
          var key81 = null;
          var val82 = null;
          key81 = input.readString().value;
          val82 = input.readString().value;
          this.jarProperties[key81] = val82;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.STRUCT) {
        this.jobStatus = new Status();
        this.jobStatus.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobDetail.prototype.write = function(output) {
  output.writeStructBegin('JobDetail');
  if (this.jobId !== null && this.jobId !== undefined) {
    output.writeFieldBegin('jobId', Thrift.Type.STRING, 1);
    output.writeString(this.jobId);
    output.writeFieldEnd();
  }
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 2);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.jar !== null && this.jar !== undefined) {
    output.writeFieldBegin('jar', Thrift.Type.STRING, 3);
    output.writeString(this.jar);
    output.writeFieldEnd();
  }
  if (this.jarMainClass !== null && this.jarMainClass !== undefined) {
    output.writeFieldBegin('jarMainClass', Thrift.Type.STRING, 4);
    output.writeString(this.jarMainClass);
    output.writeFieldEnd();
  }
  if (this.jarArgs !== null && this.jarArgs !== undefined) {
    output.writeFieldBegin('jarArgs', Thrift.Type.LIST, 5);
    output.writeListBegin(Thrift.Type.STRING, this.jarArgs.length);
    for (var iter83 in this.jarArgs)
    {
      if (this.jarArgs.hasOwnProperty(iter83))
      {
        iter83 = this.jarArgs[iter83];
        output.writeString(iter83);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.jarProperties !== null && this.jarProperties !== undefined) {
    output.writeFieldBegin('jarProperties', Thrift.Type.MAP, 6);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRING, Thrift.objectLength(this.jarProperties));
    for (var kiter84 in this.jarProperties)
    {
      if (this.jarProperties.hasOwnProperty(kiter84))
      {
        var viter85 = this.jarProperties[kiter84];
        output.writeString(kiter84);
        output.writeString(viter85);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  if (this.jobStatus !== null && this.jobStatus !== undefined) {
    output.writeFieldBegin('jobStatus', Thrift.Type.STRUCT, 7);
    this.jobStatus.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

InstanceGroupDetail = function(args) {
  this.groupId = null;
  this.name = null;
  this.role = null;
  this.instanceType = null;
  this.requestedInstanceCount = null;
  this.runningInstanceCount = null;
  this.instanceStatus = null;
  if (args) {
    if (args.groupId !== undefined) {
      this.groupId = args.groupId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field groupId is unset!');
    }
    if (args.name !== undefined) {
      this.name = args.name;
    }
    if (args.role !== undefined) {
      this.role = args.role;
    }
    if (args.instanceType !== undefined) {
      this.instanceType = args.instanceType;
    }
    if (args.requestedInstanceCount !== undefined) {
      this.requestedInstanceCount = args.requestedInstanceCount;
    }
    if (args.runningInstanceCount !== undefined) {
      this.runningInstanceCount = args.runningInstanceCount;
    }
    if (args.instanceStatus !== undefined) {
      this.instanceStatus = args.instanceStatus;
    }
  }
};
InstanceGroupDetail.prototype = {};
InstanceGroupDetail.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.groupId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.role = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.instanceType = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I32) {
        this.requestedInstanceCount = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.I32) {
        this.runningInstanceCount = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.STRUCT) {
        this.instanceStatus = new Status();
        this.instanceStatus.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InstanceGroupDetail.prototype.write = function(output) {
  output.writeStructBegin('InstanceGroupDetail');
  if (this.groupId !== null && this.groupId !== undefined) {
    output.writeFieldBegin('groupId', Thrift.Type.STRING, 1);
    output.writeString(this.groupId);
    output.writeFieldEnd();
  }
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 2);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.role !== null && this.role !== undefined) {
    output.writeFieldBegin('role', Thrift.Type.I32, 3);
    output.writeI32(this.role);
    output.writeFieldEnd();
  }
  if (this.instanceType !== null && this.instanceType !== undefined) {
    output.writeFieldBegin('instanceType', Thrift.Type.STRING, 4);
    output.writeString(this.instanceType);
    output.writeFieldEnd();
  }
  if (this.requestedInstanceCount !== null && this.requestedInstanceCount !== undefined) {
    output.writeFieldBegin('requestedInstanceCount', Thrift.Type.I32, 5);
    output.writeI32(this.requestedInstanceCount);
    output.writeFieldEnd();
  }
  if (this.runningInstanceCount !== null && this.runningInstanceCount !== undefined) {
    output.writeFieldBegin('runningInstanceCount', Thrift.Type.I32, 6);
    output.writeI32(this.runningInstanceCount);
    output.writeFieldEnd();
  }
  if (this.instanceStatus !== null && this.instanceStatus !== undefined) {
    output.writeFieldBegin('instanceStatus', Thrift.Type.STRUCT, 7);
    this.instanceStatus.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ClusterDetail = function(args) {
  this.clusterId = null;
  this.name = null;
  this.region = null;
  this.purpose = null;
  this.keyPair = null;
  this.autoTerminate = null;
  this.terminationProtected = null;
  this.instanceGroups = null;
  this.masterPublicDnsName = null;
  this.clusterStatus = null;
  if (args) {
    if (args.clusterId !== undefined) {
      this.clusterId = args.clusterId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field clusterId is unset!');
    }
    if (args.name !== undefined) {
      this.name = args.name;
    }
    if (args.region !== undefined) {
      this.region = args.region;
    }
    if (args.purpose !== undefined) {
      this.purpose = args.purpose;
    }
    if (args.keyPair !== undefined) {
      this.keyPair = args.keyPair;
    }
    if (args.autoTerminate !== undefined) {
      this.autoTerminate = args.autoTerminate;
    }
    if (args.terminationProtected !== undefined) {
      this.terminationProtected = args.terminationProtected;
    }
    if (args.instanceGroups !== undefined) {
      this.instanceGroups = args.instanceGroups;
    }
    if (args.masterPublicDnsName !== undefined) {
      this.masterPublicDnsName = args.masterPublicDnsName;
    }
    if (args.clusterStatus !== undefined) {
      this.clusterStatus = args.clusterStatus;
    }
  }
};
ClusterDetail.prototype = {};
ClusterDetail.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.clusterId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.region = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.purpose = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.keyPair = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.BOOL) {
        this.autoTerminate = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.BOOL) {
        this.terminationProtected = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.LIST) {
        var _size86 = 0;
        var _rtmp390;
        this.instanceGroups = [];
        var _etype89 = 0;
        _rtmp390 = input.readListBegin();
        _etype89 = _rtmp390.etype;
        _size86 = _rtmp390.size;
        for (var _i91 = 0; _i91 < _size86; ++_i91)
        {
          var elem92 = null;
          elem92 = new InstanceGroupDetail();
          elem92.read(input);
          this.instanceGroups.push(elem92);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 9:
      if (ftype == Thrift.Type.STRING) {
        this.masterPublicDnsName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 10:
      if (ftype == Thrift.Type.STRUCT) {
        this.clusterStatus = new Status();
        this.clusterStatus.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ClusterDetail.prototype.write = function(output) {
  output.writeStructBegin('ClusterDetail');
  if (this.clusterId !== null && this.clusterId !== undefined) {
    output.writeFieldBegin('clusterId', Thrift.Type.STRING, 1);
    output.writeString(this.clusterId);
    output.writeFieldEnd();
  }
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 2);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.region !== null && this.region !== undefined) {
    output.writeFieldBegin('region', Thrift.Type.STRING, 3);
    output.writeString(this.region);
    output.writeFieldEnd();
  }
  if (this.purpose !== null && this.purpose !== undefined) {
    output.writeFieldBegin('purpose', Thrift.Type.STRING, 4);
    output.writeString(this.purpose);
    output.writeFieldEnd();
  }
  if (this.keyPair !== null && this.keyPair !== undefined) {
    output.writeFieldBegin('keyPair', Thrift.Type.STRING, 5);
    output.writeString(this.keyPair);
    output.writeFieldEnd();
  }
  if (this.autoTerminate !== null && this.autoTerminate !== undefined) {
    output.writeFieldBegin('autoTerminate', Thrift.Type.BOOL, 6);
    output.writeBool(this.autoTerminate);
    output.writeFieldEnd();
  }
  if (this.terminationProtected !== null && this.terminationProtected !== undefined) {
    output.writeFieldBegin('terminationProtected', Thrift.Type.BOOL, 7);
    output.writeBool(this.terminationProtected);
    output.writeFieldEnd();
  }
  if (this.instanceGroups !== null && this.instanceGroups !== undefined) {
    output.writeFieldBegin('instanceGroups', Thrift.Type.LIST, 8);
    output.writeListBegin(Thrift.Type.STRUCT, this.instanceGroups.length);
    for (var iter93 in this.instanceGroups)
    {
      if (this.instanceGroups.hasOwnProperty(iter93))
      {
        iter93 = this.instanceGroups[iter93];
        iter93.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.masterPublicDnsName !== null && this.masterPublicDnsName !== undefined) {
    output.writeFieldBegin('masterPublicDnsName', Thrift.Type.STRING, 9);
    output.writeString(this.masterPublicDnsName);
    output.writeFieldEnd();
  }
  if (this.clusterStatus !== null && this.clusterStatus !== undefined) {
    output.writeFieldBegin('clusterStatus', Thrift.Type.STRUCT, 10);
    this.clusterStatus.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SetConfigRequest = function(args) {
  this.cluster = null;
  this.config = null;
  if (args) {
    if (args.cluster !== undefined) {
      this.cluster = args.cluster;
    }
    if (args.config !== undefined) {
      this.config = args.config;
    }
  }
};
SetConfigRequest.prototype = {};
SetConfigRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.cluster = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.config = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SetConfigRequest.prototype.write = function(output) {
  output.writeStructBegin('SetConfigRequest');
  if (this.cluster !== null && this.cluster !== undefined) {
    output.writeFieldBegin('cluster', Thrift.Type.STRING, 1);
    output.writeString(this.cluster);
    output.writeFieldEnd();
  }
  if (this.config !== null && this.config !== undefined) {
    output.writeFieldBegin('config', Thrift.Type.STRING, 2);
    output.writeString(this.config);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SetConfigResponse = function(args) {
  this.succeed = null;
  if (args) {
    if (args.succeed !== undefined) {
      this.succeed = args.succeed;
    }
  }
};
SetConfigResponse.prototype = {};
SetConfigResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.BOOL) {
        this.succeed = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SetConfigResponse.prototype.write = function(output) {
  output.writeStructBegin('SetConfigResponse');
  if (this.succeed !== null && this.succeed !== undefined) {
    output.writeFieldBegin('succeed', Thrift.Type.BOOL, 1);
    output.writeBool(this.succeed);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StartServiceRequest = function(args) {
  this.cluster = null;
  this.services = null;
  if (args) {
    if (args.cluster !== undefined) {
      this.cluster = args.cluster;
    }
    if (args.services !== undefined) {
      this.services = args.services;
    }
  }
};
StartServiceRequest.prototype = {};
StartServiceRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.cluster = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.LIST) {
        var _size94 = 0;
        var _rtmp398;
        this.services = [];
        var _etype97 = 0;
        _rtmp398 = input.readListBegin();
        _etype97 = _rtmp398.etype;
        _size94 = _rtmp398.size;
        for (var _i99 = 0; _i99 < _size94; ++_i99)
        {
          var elem100 = null;
          elem100 = input.readString().value;
          this.services.push(elem100);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StartServiceRequest.prototype.write = function(output) {
  output.writeStructBegin('StartServiceRequest');
  if (this.cluster !== null && this.cluster !== undefined) {
    output.writeFieldBegin('cluster', Thrift.Type.STRING, 1);
    output.writeString(this.cluster);
    output.writeFieldEnd();
  }
  if (this.services !== null && this.services !== undefined) {
    output.writeFieldBegin('services', Thrift.Type.LIST, 2);
    output.writeListBegin(Thrift.Type.STRING, this.services.length);
    for (var iter101 in this.services)
    {
      if (this.services.hasOwnProperty(iter101))
      {
        iter101 = this.services[iter101];
        output.writeString(iter101);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StartServiceResponse = function(args) {
  this.succeed = null;
  if (args) {
    if (args.succeed !== undefined) {
      this.succeed = args.succeed;
    }
  }
};
StartServiceResponse.prototype = {};
StartServiceResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.BOOL) {
        this.succeed = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StartServiceResponse.prototype.write = function(output) {
  output.writeStructBegin('StartServiceResponse');
  if (this.succeed !== null && this.succeed !== undefined) {
    output.writeFieldBegin('succeed', Thrift.Type.BOOL, 1);
    output.writeBool(this.succeed);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StopServiceRequest = function(args) {
  this.cluster = null;
  this.services = null;
  if (args) {
    if (args.cluster !== undefined) {
      this.cluster = args.cluster;
    }
    if (args.services !== undefined) {
      this.services = args.services;
    }
  }
};
StopServiceRequest.prototype = {};
StopServiceRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.cluster = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.LIST) {
        var _size102 = 0;
        var _rtmp3106;
        this.services = [];
        var _etype105 = 0;
        _rtmp3106 = input.readListBegin();
        _etype105 = _rtmp3106.etype;
        _size102 = _rtmp3106.size;
        for (var _i107 = 0; _i107 < _size102; ++_i107)
        {
          var elem108 = null;
          elem108 = input.readString().value;
          this.services.push(elem108);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StopServiceRequest.prototype.write = function(output) {
  output.writeStructBegin('StopServiceRequest');
  if (this.cluster !== null && this.cluster !== undefined) {
    output.writeFieldBegin('cluster', Thrift.Type.STRING, 1);
    output.writeString(this.cluster);
    output.writeFieldEnd();
  }
  if (this.services !== null && this.services !== undefined) {
    output.writeFieldBegin('services', Thrift.Type.LIST, 2);
    output.writeListBegin(Thrift.Type.STRING, this.services.length);
    for (var iter109 in this.services)
    {
      if (this.services.hasOwnProperty(iter109))
      {
        iter109 = this.services[iter109];
        output.writeString(iter109);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StopServiceResponse = function(args) {
  this.succeed = null;
  if (args) {
    if (args.succeed !== undefined) {
      this.succeed = args.succeed;
    }
  }
};
StopServiceResponse.prototype = {};
StopServiceResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.BOOL) {
        this.succeed = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StopServiceResponse.prototype.write = function(output) {
  output.writeStructBegin('StopServiceResponse');
  if (this.succeed !== null && this.succeed !== undefined) {
    output.writeFieldBegin('succeed', Thrift.Type.BOOL, 1);
    output.writeBool(this.succeed);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ClusterState = function(args) {
  this.ready = null;
  this.timeline = null;
  this.hostReady = null;
  this.serviceReady = null;
  if (args) {
    if (args.ready !== undefined) {
      this.ready = args.ready;
    }
    if (args.timeline !== undefined) {
      this.timeline = args.timeline;
    }
    if (args.hostReady !== undefined) {
      this.hostReady = args.hostReady;
    }
    if (args.serviceReady !== undefined) {
      this.serviceReady = args.serviceReady;
    }
  }
};
ClusterState.prototype = {};
ClusterState.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.BOOL) {
        this.ready = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.timeline = new Timeline();
        this.timeline.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BOOL) {
        this.hostReady = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.BOOL) {
        this.serviceReady = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ClusterState.prototype.write = function(output) {
  output.writeStructBegin('ClusterState');
  if (this.ready !== null && this.ready !== undefined) {
    output.writeFieldBegin('ready', Thrift.Type.BOOL, 1);
    output.writeBool(this.ready);
    output.writeFieldEnd();
  }
  if (this.timeline !== null && this.timeline !== undefined) {
    output.writeFieldBegin('timeline', Thrift.Type.STRUCT, 2);
    this.timeline.write(output);
    output.writeFieldEnd();
  }
  if (this.hostReady !== null && this.hostReady !== undefined) {
    output.writeFieldBegin('hostReady', Thrift.Type.BOOL, 3);
    output.writeBool(this.hostReady);
    output.writeFieldEnd();
  }
  if (this.serviceReady !== null && this.serviceReady !== undefined) {
    output.writeFieldBegin('serviceReady', Thrift.Type.BOOL, 4);
    output.writeBool(this.serviceReady);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

DEFAULT_SERVICE_ENDPOINT = 'http://emr.api.xiaomi.com';
DEFAULT_SECURE_SERVICE_ENDPOINT = 'https://emr.api.xiaomi.com';
API_ROOT_PATH = '/v1/api';
SCHEDULER_SERVICE_PATH = '/v1/api/scheduler';
MASTER_SERVICE_PATH = '/v1/api/master';
